name: MobCustom
version: '0.1'
main: etb_mob_custom.CustomMobLoader
api-version: '1.21'
softdepend: [Multiverse-Core]

commands:
  pet:
    description: Fait apparaître un compagnon personnalisé
    usage: /pet <mobId>
    permission: custommob.spawn

permissions:
  custommob.spawn:
    description: Permet d'utiliser la commande /pet
    default: op
  custommob.spawn.*:
    description: Permet de faire apparaître n'importe quel type de compagnon
    default: op
    children:
      custommob.spawn: true